version: "3.9"
networks:
  development:
    name: dev
services:
  backend_dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend_dev
    restart: always
    volumes:
      - ./backend:/app
    ports: 
      - "8050:8050"
    networks:
      - development
  